[package]
name = "chapter_1-3"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
